; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "EasyDownload"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "p4rs"
#define MyAppURL "https://www.easydownload.net/"
#define MyAppExeName "EasyDownload.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FB4A6D48-4CD2-4CDC-8C27-65EEAB2C6892}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\setup\license.txt
InfoBeforeFile=C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\setup\before_install.txt
InfoAfterFile=C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\setup\after_install.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\setup
OutputBaseFilename=EasyDownload-Setup-1.1.0
SetupIconFile=C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\assets\logos\logo.ico
SolidCompression=yes
WizardStyle=classic zircon

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\core.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\parso\Desktop\Projeler\easydownload\versions\1.1.0\assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\logos\logo.ico"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\assets\logos\logo.ico"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function GetAppLangCode(InstallerLang: String): String;
begin
  Result := 'en';
  if InstallerLang = 'turkish' then Result := 'tr'
  else if InstallerLang = 'arabic' then Result := 'ar'
  else if InstallerLang = 'french' then Result := 'fr'
  else if InstallerLang = 'german' then Result := 'de'
  else if InstallerLang = 'italian' then Result := 'it'
  else if InstallerLang = 'portuguese' then Result := 'pt'
  else if InstallerLang = 'russian' then Result := 'ru'
  else if InstallerLang = 'spanish' then Result := 'es';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  SettingsPath: String;
  FileContentAnsi: AnsiString;
  FileContent: String;
  LangCode: String;
begin
  if CurStep = ssPostInstall then
  begin
    SettingsPath := ExpandConstant('{app}\data\settings.json');
    LangCode := GetAppLangCode(ActiveLanguage());

    if LoadStringFromFile(SettingsPath, FileContentAnsi) then
    begin
      FileContent := String(FileContentAnsi);
      StringChangeEx(FileContent, '"language" : "en"', '"language" : "' + LangCode + '"', True);
      StringChangeEx(FileContent, '"language": "en"', '"language": "' + LangCode + '"', True);
      StringChangeEx(FileContent, '"language":"en"', '"language":"' + LangCode + '"', True);

      SaveStringToFile(SettingsPath, AnsiString(FileContent), False);
    end;
  end;
end;